CREATE TABLE sso_stepup (
 id TEXT PRIMARY KEY,
 session_id TEXT NOT NULL UNIQUE REFERENCES sessions(id) ON DELETE CASCADE,
 action TEXT NOT NULL,
 created_at INTEGER NOT NULL,
 expires_at INTEGER NOT NULL,
 started INTEGER NOT NULL DEFAULT 0,
 verified INTEGER NOT NULL DEFAULT 0,
 auth_time INTEGER NOT NULL DEFAULT 0,
 proof_sid TEXT NOT NULL DEFAULT '',
 proof_iat INTEGER NOT NULL DEFAULT 0
);
